//import os from 'os'
const os = require('os')
console.log(os.platform())
console.log(os.arch())
console.log(os.freemem())
console.log(os.userInfo())
console.log(os.homedir())
console.log(os.version())
console.log(os.type())
console.log(os.cpus())